import fs from "node:fs/promises";
import path from "node:path";

export function isCompletePdf(buffer) {
  // Basic completeness check, not a guarantee that the captured article is correct.
  return buffer.subarray(0, 5).toString() === "%PDF-" &&
    buffer.subarray(-1024).includes(Buffer.from("%%EOF"));
}

export async function inspectPdf(filename) {
  let buffer;
  try {
    buffer = await fs.readFile(filename);
  } catch (error) {
    if (error.code === "ENOENT") return { exists: false, valid: false };
    throw error;
  }
  return {
    exists: true,
    valid: isCompletePdf(buffer),
    stats: await fs.stat(filename),
  };
}

export async function logIssue(root, issue) {
  const filename = path.join(root, "archive-issues.log");
  let previous = "";
  try { previous = await fs.readFile(filename, "utf8"); }
  catch (error) { if (error.code !== "ENOENT") throw error; }
  const line = JSON.stringify(issue);
  // Refreshing tasks from the same report must not duplicate historical entries.
  if (!previous.split("\n").includes(line)) await fs.appendFile(filename, line + "\n");
}

function segment(value) {
  return String(value).normalize("NFKD").replace(/[^\w.-]+/g, "-").replace(/^-+|-+$/g, "").toLowerCase();
}
function oneLine(value) { return String(value).replace(/\s+/g, " ").trim(); }

export async function writeManualTasks(root, articles, report) {
  const lines = [
    "# Manual tasks todo for me", "",
    "Generated by the archiver. This file is replaced on each run; keep personal notes elsewhere.", "",
    "Open each source and download the article PDF, or use Print → Save as PDF. Check its content, then save it at the exact path below (relative to this repository).",
    "Run `npm run archive:tasks` to refresh this checklist without downloading, or `npm run archive` to retry missing articles. Existing complete PDFs are skipped automatically.", "",
  ];
  let count = 0;
  for (const article of articles) {
    const output = `pdfs/${segment(article.category || "uncategorized")}/${segment(article.id || article.title)}.pdf`;
    const pdf = await inspectPdf(path.join(root, output));
    if (pdf.valid) continue;
    count++;
    const issue = report.find(item => item.id === article.id && ["blocked", "failed"].includes(item.status));
    lines.push(`- [ ] **${oneLine(article.title)}**`,
      `  - Source: <${article.url}>`,
      `  - Save as: \`${output}\``,
      `  - Issue: ${oneLine(pdf.exists ? "Existing file failed the PDF completeness check. Inspect or replace it; it will not be overwritten." : issue?.error || "PDF is missing; no recorded download error.")}`,
      ...(issue?.httpStatus === 404 ? ["  - Action: find the article on the author's or publisher's site; update its URL in articles.yaml if it moved."] : []), "");
  }
  if (!count) lines.push("No manual downloads pending.", "");
  await fs.writeFile(path.join(root, "manual-tasks-todo-for-me.md"), lines.join("\n"));
  return count;
}

// The deadline covers redirects, response headers, and the entire response body.
export async function fetchPdfBuffer(url, { required = false, timeoutMs = 60000 } = {}) {
  const signal = AbortSignal.timeout(timeoutMs);
  let response;
  try {
    response = await fetch(url, { signal });
    const contentType = response.headers.get("content-type") || "";
    const isPdf = contentType.toLowerCase().split(";")[0].trim() === "application/pdf";
    // Leave HTML responses (including browser challenges) to Playwright.
    if (!isPdf && !required) return null;
    if (!response.ok) {
      const error = new Error(`HTTP ${response.status} ${response.statusText}`);
      error.httpStatus = response.status;
      throw error;
    }
    if (!isPdf) throw new Error(`Expected a PDF but received: ${contentType || "unknown content type"}`);
    const buffer = Buffer.from(await response.arrayBuffer());
    if (!isCompletePdf(buffer)) {
      throw new Error("Downloaded content failed the PDF completeness check (missing %PDF- header or %%EOF end marker).");
    }
    return buffer;
  } catch (error) {
    if (signal.aborted) throw new Error(`Download timed out after ${timeoutMs} ms: ${url}`);
    throw error;
  } finally {
    if (response?.body && !response.bodyUsed) await response.body.cancel().catch(() => {});
  }
}
