import fs from "node:fs/promises";
import path from "node:path";

export async function inspectPdf(filename) {
  let buffer;
  try {
    buffer = await fs.readFile(filename);
  } catch (error) {
    if (error.code === "ENOENT") return { exists: false, valid: false };
    throw error;
  }
  return {
    exists: true,
    // Basic completeness check, not a guarantee that the captured article is correct.
    valid: buffer.subarray(0, 5).toString() === "%PDF-" && buffer.subarray(-1024).includes(Buffer.from("%%EOF")),
    stats: await fs.stat(filename),
  };
}

export async function logIssue(root, issue) {
  const filename = path.join(root, "archive-issues.log");
  let previous = "";
  try { previous = await fs.readFile(filename, "utf8"); }
  catch (error) { if (error.code !== "ENOENT") throw error; }
  const line = JSON.stringify(issue);
  // Refreshing tasks from the same report must not duplicate historical entries.
  if (!previous.split("\n").includes(line)) await fs.appendFile(filename, line + "\n");
}

function segment(value) {
  return String(value).normalize("NFKD").replace(/[^\w.-]+/g, "-").replace(/^-+|-+$/g, "").toLowerCase();
}
function oneLine(value) { return String(value).replace(/\s+/g, " ").trim(); }

export async function writeManualTasks(root, articles, report) {
  const lines = [
    "# Manual tasks todo for me", "",
    "Generated by the archiver. This file is replaced on each run; keep personal notes elsewhere.", "",
    "Open each source and download the article PDF, or use Print → Save as PDF. Check its content, then save it at the exact path below (relative to this repository).",
    "Run `npm run archive:tasks` to refresh this checklist without downloading, or `npm run archive` to retry missing articles. Existing complete PDFs are skipped automatically.", "",
  ];
  let count = 0;
  for (const article of articles) {
    const output = `pdfs/${segment(article.category || "uncategorized")}/${segment(article.id || article.title)}.pdf`;
    const pdf = await inspectPdf(path.join(root, output));
    if (pdf.valid) continue;
    count++;
    const issue = report.find(item => item.id === article.id && ["blocked", "failed"].includes(item.status));
    lines.push(`- [ ] **${oneLine(article.title)}**`,
      `  - Source: <${article.url}>`,
      `  - Save as: \`${output}\``,
      `  - Issue: ${oneLine(pdf.exists ? "Existing file failed the PDF completeness check. Inspect or replace it; it will not be overwritten." : issue?.error || "PDF is missing; no recorded download error.")}`,
      ...(issue?.httpStatus === 404 ? ["  - Action: find the article on the author's or publisher's site; update its URL in articles.yaml if it moved."] : []), "");
  }
  if (!count) lines.push("No manual downloads pending.", "");
  await fs.writeFile(path.join(root, "manual-tasks-todo-for-me.md"), lines.join("\n"));
  return count;
}
