import fs from "node:fs/promises";
import path from "node:path";
import { articlePdfPath } from "./article-library.mjs";

export function isCompletePdf(buffer) {
  // Basic completeness check, not a guarantee that the captured article is correct.
  return buffer.subarray(0, 5).toString() === "%PDF-" &&
    buffer.subarray(-1024).includes(Buffer.from("%%EOF"));
}

// Stage on the destination filesystem, then publish with an atomic no-clobber link.
// A file created by another process while downloading must never be replaced.
export async function publishPdf(filename, buffer) {
  if (!isCompletePdf(buffer)) throw new Error("PDF failed the completeness check; no source was published.");
  await fs.mkdir(path.dirname(filename), { recursive: true });
  const temporaryDirectory = await fs.mkdtemp(path.join(path.dirname(filename), ".pdf-capture-"));
  try {
    const temporaryFile = path.join(temporaryDirectory, "capture.pdf");
    await fs.writeFile(temporaryFile, buffer, { flag: "wx" });
    try {
      await fs.link(temporaryFile, filename);
    } catch (error) {
      if (error.code === "EEXIST") {
        throw new Error(`A file appeared during capture and was preserved: ${filename}. Rerun to inspect or skip it.`, { cause: error });
      }
      throw error;
    }
  } finally {
    await fs.rm(temporaryDirectory, { recursive: true, force: true });
  }
}

export async function inspectPdf(filename) {
  let buffer;
  try {
    buffer = await fs.readFile(filename);
  } catch (error) {
    if (error.code === "ENOENT") return { exists: false, valid: false };
    throw error;
  }
  return {
    exists: true,
    valid: isCompletePdf(buffer),
    stats: await fs.stat(filename),
  };
}

export async function logIssue(root, issue) {
  const filename = path.join(root, "archive-issues.log");
  let previous = "";
  try { previous = await fs.readFile(filename, "utf8"); }
  catch (error) { if (error.code !== "ENOENT") throw error; }
  const line = JSON.stringify(issue);
  // Refreshing tasks from the same report must not duplicate historical entries.
  if (!previous.split("\n").includes(line)) await fs.appendFile(filename, line + "\n");
}

function oneLine(value) { return String(value).replace(/\s+/g, " ").trim(); }

export async function writeManualTasks(root, articles, report) {
  const lines = [
    "# Manual tasks todo for me", "",
    "Generated by the archiver. This file is replaced on each run; keep personal notes elsewhere.", "",
    "Open each source and download the article PDF, or use Print → Save as PDF. Check its content, then save it at the exact path below (relative to this repository).",
    "Run `npm run archive:tasks` to refresh this checklist without downloading, or `npm run archive` to retry missing articles. Existing complete PDFs are skipped automatically.", "",
  ];
  let count = 0;
  for (const article of articles) {
    const output = articlePdfPath(article);
    const pdf = await inspectPdf(path.join(root, output));
    if (pdf.valid) continue;
    count++;
    const issue = report.find(item => item.id === article.id && ["blocked", "failed"].includes(item.status));
    lines.push(`- [ ] **${oneLine(article.title)}**`,
      `  - Source: ${article.url ? `<${article.url}>` : "URL missing; add it to articles.yaml or supply a PDF manually."}`,
      `  - Save as: \`${output}\``,
      `  - Issue: ${oneLine(pdf.exists ? "Existing file failed the PDF completeness check. Inspect or replace it; it will not be overwritten." : issue?.error || "PDF is missing; no recorded download error.")}`,
      ...(issue?.httpStatus === 404 ? ["  - Action: find the article on the author's or publisher's site; update its URL in articles.yaml if it moved."] : []), "");
  }
  if (!count) lines.push("No manual downloads pending.", "");
  await fs.writeFile(path.join(root, "manual-tasks-todo-for-me.md"), lines.join("\n"));
  return count;
}

// The deadline covers redirects, response headers, and the entire response body.
export async function fetchPdfBuffer(url, { required = false, timeoutMs = 60000 } = {}) {
  const signal = AbortSignal.timeout(timeoutMs);
  let response;
  try {
    response = await fetch(url, { signal });
    const contentType = response.headers.get("content-type") || "";
    const mime = contentType.toLowerCase().split(";")[0].trim();
    const isPdf = ["application/pdf", "application/x-pdf"].includes(mime);
    const disposition = response.headers.get("content-disposition") || "";
    const pdfAttachment = /filename\*?\s*=\s*[^;]*\.pdf(?:["'\s;]|$)/i.test(disposition);
    const binary = ["application/octet-stream", "binary/octet-stream", ""].includes(mime);
    // Leave ordinary HTML responses (including browser challenges) to Playwright.
    if (!isPdf && !required && !binary && !pdfAttachment) return null;
    if (!response.ok) {
      const error = new Error(`HTTP ${response.status} ${response.statusText}`);
      error.httpStatus = response.status;
      throw error;
    }
    const buffer = Buffer.from(await response.arrayBuffer());
    if (!isCompletePdf(buffer)) {
      // A generic or missing MIME type alone does not establish that this is a PDF.
      const hasPdfHeader = buffer.subarray(0, 5).toString() === "%PDF-";
      if (!isPdf && !required && !pdfAttachment && !hasPdfHeader) return null;
      throw new Error("Downloaded content failed the PDF completeness check (missing %PDF- header or %%EOF end marker).");
    }
    return buffer;
  } catch (error) {
    if (signal.aborted) throw new Error(`Download timed out after ${timeoutMs} ms: ${url}`);
    throw error;
  } finally {
    if (response?.body && !response.bodyUsed) await response.body.cancel().catch(() => {});
  }
}
