import fs from "node:fs/promises";
import path from "node:path";
import YAML from "yaml";

export function sanitizeSegment(value) {
  return String(value)
    .normalize("NFKD")
    .replace(/[^\w.-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase();
}

export function articlePdfPath(article) {
  return `articles/${sanitizeSegment(article.id)}/source.pdf`;
}

export async function readConfiguration(root) {
  const raw = await fs.readFile(path.join(root, "articles.yaml"), "utf8");
  const configuration = YAML.parse(raw);

  if (!configuration?.articles || !Array.isArray(configuration.articles)) {
    throw new Error(
      "articles.yaml must contain an 'articles' array.",
    );
  }

  const destinations = new Map();
  for (const [index, article] of configuration.articles.entries()) {
    const label = `Article ${index + 1}`;
    if (!article || typeof article !== "object" || Array.isArray(article)) {
      throw new Error(`${label} must be an object; remove empty list items in articles.yaml.`);
    }
    for (const field of ["id", "title", "category"]) {
      if (typeof article[field] !== "string" || !article[field].trim()) {
        throw new Error(`${label} requires a nonempty ${field} string.`);
      }
    }
    // Bibliographic entries may have no URL yet; keep them in the knowledge base.
    if (article.url != null) {
      if (typeof article.url !== "string" || !article.url.trim()) {
        throw new Error(`${label} requires a nonempty url string or null.`);
      }
      const url = new URL(article.url);
      if (!["http:", "https:"].includes(url.protocol)) {
        throw new Error(`${label} requires an HTTP or HTTPS URL.`);
      }
    }
    const id = sanitizeSegment(article.id);
    const category = sanitizeSegment(article.category);
    if ([id, category].some(value => !value || value === "." || value === "..")) {
      throw new Error(`${label} has an invalid id or category for its PDF path.`);
    }
    const destination = path.join("articles", id, "source.pdf");
    if (destinations.has(destination)) {
      throw new Error(`${label} and article ${destinations.get(destination)} resolve to the same PDF path: ${destination}. Give them globally distinct IDs.`);
    }
    destinations.set(destination, index + 1);
  }
  return configuration.articles;
}

// Count Unicode letter/number groups; internal apostrophes and hyphens stay in a word.
export function countWords(text) {
  return (text.match(/[\p{L}\p{N}][\p{L}\p{M}\p{N}]*(?:['’\-][\p{L}\p{N}][\p{L}\p{M}\p{N}]*)*/gu) || []).length;
}

// Index fields remain authoritative; word_count is derived from the local Markdown.
export async function syncMetadata(root, articles) {
  const qualityRows = [];
  for (const article of articles) {
    const directory = path.dirname(path.join(root, articlePdfPath(article)));
    const filename = path.join(directory, "metadata.yaml");
    let wordCount = null;
    try { wordCount = countWords(await fs.readFile(path.join(directory, "article.md"), "utf8")); }
    catch (error) { if (error.code !== "ENOENT") throw error; }
    let previous;
    try { previous = await fs.readFile(filename, "utf8"); }
    catch (error) { if (error.code !== "ENOENT") throw error; }
    // Keep the human decision separate from regenerated index fields and checks.
    const review = (previous ? YAML.parse(previous)?.quality_review : null) || { status: "pending", notes: null };
    if (!["pending", "approved", "rejected"].includes(review.status) ||
        (review.notes != null && typeof review.notes !== "string")) {
      throw new Error(`Invalid quality_review in ${filename}; use pending, approved, or rejected and text notes.`);
    }
    let sources = [];
    try {
      sources = (await fs.readdir(directory, { withFileTypes: true }))
        .filter(entry => entry.isFile() && /^source\./.test(entry.name));
    } catch (error) { if (error.code !== "ENOENT") throw error; }
    const issues = [];
    if (!sources.length) issues.push("missing_source");
    if (wordCount === null) issues.push("missing_markdown");
    else if (wordCount === 0) issues.push("empty_markdown");
    if (review.status === "rejected") issues.push("review_rejected");
    const quality = { status: issues.length ? "needs_review" : review.status === "approved" ? "ok" : "not_reviewed", issues };
    qualityRows.push({ article, quality, review, wordCount });
    const content = YAML.stringify({ ...article, word_count: wordCount, quality, quality_review: review });
    if (previous === content) continue;
    await fs.mkdir(directory, { recursive: true });
    await fs.writeFile(filename, content, "utf8");
  }
  const oneLine = value => String(value ?? "").replace(/\s+/g, " ").replaceAll("|", "\\|").trim();
  const lines = ["# Article quality", "", "Generated by metadata synchronization. Edit quality_review in an article's metadata.yaml to retain a human decision.", "",
    `Needs review: ${qualityRows.filter(row => row.quality.status === "needs_review").length}. Not reviewed: ${qualityRows.filter(row => row.quality.status === "not_reviewed").length}. Approved without detected issues: ${qualityRows.filter(row => row.quality.status === "ok").length}.`, "",
    "Successful text extraction does not establish that a source is complete or that tables, images, and reading order are faithful.", "",
    "| Article | Status | Issues | Words | Review notes |", "|---|---|---|---:|---|"];
  for (const { article, quality, review, wordCount } of qualityRows) {
    const metadataPath = path.posix.join(path.posix.dirname(articlePdfPath(article)), "metadata.yaml");
    lines.push(`| [${oneLine(article.title).replaceAll("[", "\\[").replaceAll("]", "\\]")}](${metadataPath}) | ${quality.status} | ${quality.issues.join(", ") || "—"} | ${wordCount ?? "—"} | ${oneLine(review.notes) || "—"} |`);
  }
  const reportPath = path.join(root, "article-quality.md");
  const report = lines.join("\n") + "\n";
  let oldReport;
  try { oldReport = await fs.readFile(reportPath, "utf8"); }
  catch (error) { if (error.code !== "ENOENT") throw error; }
  if (oldReport !== report) await fs.writeFile(reportPath, report, "utf8");
}
